version: '3.0'
services:
  product:
    build:
      context: product
      dockerfile: Dockerfile
    container_name: product
    depends_on:
      - nacos
    restart: always
  user:
    build:
      context: user
      dockerfile: Dockerfile
    container_name: user
    depends_on:
      - nacos
    restart: always
